name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubunto-latest
    steps:
      - run: echo "Hello world"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in repository
        run: |
          echo "The respository ${{github.repository}} contains the following files:"
          tree
